# Generated by Django 5.1.8 on 2026-05-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0002_remove_resume_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='analysis_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='ats_score',
            field=models.IntegerField(default=0),
        ),
    ]
