# Generated by Django 5.1.8 on 2026-06-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0003_resume_analysis_data_resume_ats_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
