# Generated by Django 5.1.8 on 2026-05-27 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
        ('resume_analyzer', '0003_resume_analysis_data_resume_ats_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume_analyzer.resume'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='used_resume_context',
            field=models.BooleanField(default=False),
        ),
    ]
