# Generated by Django 5.1.8 on 2026-06-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_interviewsimulation_interviewsimulationanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsimulationanswer',
            name='question_type',
            field=models.CharField(choices=[('HR', 'HR'), ('TECHNICAL', 'Technical')], max_length=20),
        ),
    ]
