# Generated by Django 5.1.8 on 2026-06-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_alter_interviewsimulationanswer_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsimulation',
            name='analysis_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewsimulation',
            name='answer_completion_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsimulation',
            name='clarity_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsimulation',
            name='communication_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsimulation',
            name='confidence_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsimulation',
            name='overall_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsimulation',
            name='problem_solving_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsimulation',
            name='readiness_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsimulation',
            name='technical_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsimulationanswer',
            name='feedback',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewsimulationanswer',
            name='improved_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='interviewsimulationanswer',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsimulationanswer',
            name='strengths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='interviewsimulationanswer',
            name='weaknesses',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
