# Generated by Django 5.1.8 on 2026-06-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_interview_analytics_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewsimulation',
            name='status',
            field=models.CharField(choices=[('GENERATED', 'Generated'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20),
        ),
    ]
