# Generated by clean-up script

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_status_choices_generated'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE interviews_interviewsimulation DROP COLUMN IF EXISTS answer_completeness_score;",
            reverse_sql="ALTER TABLE interviews_interviewsimulation ADD COLUMN answer_completeness_score integer NULL;"
        ),
        migrations.RunSQL(
            sql="ALTER TABLE interviews_interviewsimulationanswer DROP COLUMN IF EXISTS generation_type;",
            reverse_sql="ALTER TABLE interviews_interviewsimulationanswer ADD COLUMN generation_type varchar(50) NULL;"
        ),
    ]
