# Generated by Django 5.1.8 on 2026-06-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Optional rationale explaining why the correct option is right.', null=True, verbose_name='Explanation'),
        ),
    ]
