# Generated by Django 5.1.8 on 2026-06-11 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_engine', '0002_question_explanation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.PositiveIntegerField(verbose_name='Total Questions')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Score')),
                ('percentage', models.FloatField(default=0, verbose_name='Percentage')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='IN_PROGRESS', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_tests', to='mcq_engine.topic', verbose_name='Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_tests', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'MCQ Test',
                'verbose_name_plural': 'MCQ Tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MCQAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='Selected Option')),
                ('is_correct', models.BooleanField(verbose_name='Is Correct')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='Answered At')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mcq_engine.question', verbose_name='Question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mcq_engine.mcqtest', verbose_name='MCQ Test')),
            ],
            options={
                'verbose_name': 'MCQ Answer',
                'verbose_name_plural': 'MCQ Answers',
                'constraints': [models.UniqueConstraint(fields=('test', 'question'), name='unique_test_question_answer')],
            },
        ),
        migrations.CreateModel(
            name='MCQTestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='Order')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='mcq_engine.question', verbose_name='Question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='mcq_engine.mcqtest', verbose_name='MCQ Test')),
            ],
            options={
                'verbose_name': 'MCQ Test Question',
                'verbose_name_plural': 'MCQ Test Questions',
                'ordering': ['test', 'order'],
                'constraints': [models.UniqueConstraint(fields=('test', 'order'), name='unique_test_question_order')],
            },
        ),
    ]
