# Generated by Django 5.1.8 on 2026-06-11 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_engine', '0003_mcqtest_mcqanswer_mcqtestquestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqanswer',
            name='is_correct',
            field=models.BooleanField(db_index=True, verbose_name='Is Correct'),
        ),
        migrations.AlterField(
            model_name='mcqanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_answers', to='mcq_engine.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='mcqanswer',
            name='selected_option',
            field=models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D'), ('X', "I Don't Know")], max_length=1, verbose_name='Selected Option'),
        ),
        migrations.AlterField(
            model_name='mcqtest',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentage'),
        ),
        migrations.AlterField(
            model_name='mcqtestquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_test_questions', to='mcq_engine.question', verbose_name='Question'),
        ),
        migrations.AddIndex(
            model_name='mcqtest',
            index=models.Index(fields=['-created_at'], name='mcq_engine__created_54f33f_idx'),
        ),
        migrations.AddIndex(
            model_name='mcqtest',
            index=models.Index(fields=['status'], name='mcq_engine__status_a7eb9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='mcqtestquestion',
            constraint=models.UniqueConstraint(fields=('test', 'question'), name='unique_test_question'),
        ),
    ]
