# Generated by Django 5.1.8 on 2026-06-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_engine', '0004_alter_mcqanswer_is_correct_alter_mcqanswer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqtest',
            name='ai_analysis',
            field=models.JSONField(blank=True, default=dict, help_text='Cached AI performance analysis generated by generate_ai_analysis().', verbose_name='AI Analysis'),
        ),
    ]
