# Generated by Django 5.1.8 on 2026-06-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_engine', '0005_add_ai_analysis_to_mcqtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqtest',
            name='experience_level',
            field=models.CharField(choices=[('FRESHER', 'Fresher'), ('JUNIOR', 'Junior'), ('MID_LEVEL', 'Mid-Level'), ('SENIOR', 'Senior')], default='FRESHER', max_length=20, verbose_name='Experience Level'),
        ),
    ]
