# pyrefly: ignore [missing-import]
from django.conf import settings
from django.db import models


class Topic(models.Model):
    name = models.CharField(max_length=200, verbose_name="Topic Name")

    class Meta:
        verbose_name = "Topic"
        verbose_name_plural = "Topics"

    def __str__(self):
        return self.name


class Subtopic(models.Model):
    topic = models.ForeignKey(
        Topic,
        on_delete=models.CASCADE,
        related_name="subtopics",
        verbose_name="Topic",
    )
    name = models.CharField(max_length=200, verbose_name="Subtopic Name")

    class Meta:
        verbose_name = "Subtopic"
        verbose_name_plural = "Subtopics"

    def __str__(self):
        return f"{self.topic.name} → {self.name}"


class Question(models.Model):

    class Difficulty(models.TextChoices):
        EASY   = "easy",   "Easy"
        MEDIUM = "medium", "Medium"
        HARD   = "hard",   "Hard"

    class CorrectOption(models.TextChoices):
        A = "A", "A"
        B = "B", "B"
        C = "C", "C"
        D = "D", "D"

    topic = models.ForeignKey(
        Topic,
        on_delete=models.CASCADE,
        related_name="questions",
        verbose_name="Topic",
    )
    subtopic = models.ForeignKey(
        Subtopic,
        on_delete=models.CASCADE,
        related_name="questions",
        verbose_name="Subtopic",
    )
    difficulty = models.CharField(
        max_length=10,
        choices=Difficulty.choices,
        verbose_name="Difficulty",
    )
    question = models.TextField(verbose_name="Question")
    option_a = models.CharField(max_length=500, verbose_name="Option A")
    option_b = models.CharField(max_length=500, verbose_name="Option B")
    option_c = models.CharField(max_length=500, verbose_name="Option C")
    option_d = models.CharField(max_length=500, verbose_name="Option D")
    correct_option = models.CharField(
        max_length=1,
        choices=CorrectOption.choices,
        verbose_name="Correct Option",
    )
    explanation = models.TextField(
        blank=True,
        null=True,
        verbose_name="Explanation",
        help_text="Optional rationale explaining why the correct option is right.",
    )

    class Meta:
        verbose_name = "Question"
        verbose_name_plural = "Questions"

    def __str__(self):
        return f"[{self.get_difficulty_display()}] {self.question[:60]}"


class MCQTest(models.Model):
    class Status(models.TextChoices):
        IN_PROGRESS = "IN_PROGRESS", "In Progress"
        COMPLETED = "COMPLETED", "Completed"

    class ExperienceLevel(models.TextChoices):
        FRESHER   = "FRESHER",   "Fresher"
        JUNIOR    = "JUNIOR",    "Junior"
        MID_LEVEL = "MID_LEVEL", "Mid-Level"
        SENIOR    = "SENIOR",    "Senior"

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name="mcq_tests",
        verbose_name="User",
    )
    topic = models.ForeignKey(
        Topic,
        on_delete=models.CASCADE,
        related_name="mcq_tests",
        verbose_name="Topic",
    )
    total_questions = models.PositiveIntegerField(verbose_name="Total Questions")
    score = models.PositiveIntegerField(default=0, verbose_name="Score")
    percentage = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        default=0.00,
        verbose_name="Percentage",
    )
    status = models.CharField(
        max_length=20,
        choices=Status.choices,
        default=Status.IN_PROGRESS,
        verbose_name="Status",
    )
    experience_level = models.CharField(
        max_length=20,
        choices=ExperienceLevel.choices,
        default=ExperienceLevel.FRESHER,
        verbose_name="Experience Level",
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created At")
    submitted_at = models.DateTimeField(null=True, blank=True, verbose_name="Submitted At")
    ai_analysis = models.JSONField(
        default=dict,
        blank=True,
        verbose_name="AI Analysis",
        help_text="Cached AI performance analysis generated by generate_ai_analysis().",
    )

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "MCQ Test"
        verbose_name_plural = "MCQ Tests"
        indexes = [
            models.Index(fields=["-created_at"]),
            models.Index(fields=["status"]),
        ]

    def __str__(self):
        return f"Test {self.id} - {self.user.username} - {self.topic.name} ({self.get_status_display()})"


class MCQTestQuestion(models.Model):
    test = models.ForeignKey(
        MCQTest,
        on_delete=models.CASCADE,
        related_name="test_questions",
        verbose_name="MCQ Test",
    )
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        related_name="mcq_test_questions",
        verbose_name="Question",
    )
    order = models.PositiveIntegerField(verbose_name="Order")

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["test", "order"],
                name="unique_test_question_order"
            ),
            models.UniqueConstraint(
                fields=["test", "question"],
                name="unique_test_question"
            )
        ]
        ordering = ["test", "order"]
        verbose_name = "MCQ Test Question"
        verbose_name_plural = "MCQ Test Questions"

    def __str__(self):
        return f"Test {self.test_id} - Q{self.order}: {self.question.question[:40]}"


class MCQAnswer(models.Model):
    class Options(models.TextChoices):
        A = "A", "Option A"
        B = "B", "Option B"
        C = "C", "Option C"
        D = "D", "Option D"
        X = "X", "I Don't Know"

    test = models.ForeignKey(
        MCQTest,
        on_delete=models.CASCADE,
        related_name="answers",
        verbose_name="MCQ Test",
    )
    question = models.ForeignKey(
        Question,
        on_delete=models.CASCADE,
        related_name="mcq_answers",
        verbose_name="Question",
    )
    selected_option = models.CharField(
        max_length=1,
        choices=Options.choices,
        verbose_name="Selected Option",
    )
    is_correct = models.BooleanField(db_index=True, verbose_name="Is Correct")
    answered_at = models.DateTimeField(auto_now_add=True, verbose_name="Answered At")

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["test", "question"],
                name="unique_test_question_answer"
            )
        ]
        verbose_name = "MCQ Answer"
        verbose_name_plural = "MCQ Answers"

    def __str__(self):
        return f"Test {self.test_id} - Q: {self.question_id} - Ans: {self.selected_option}"
